localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/ar.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/da.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/de.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/el.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/es.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/fil.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/fr.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/it.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/ja.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/ko.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/kk.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/nl.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/pl.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/pt-BR.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/ru.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/sv.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/th.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/tr.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/uk.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/ur.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/vi.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/zh-CN.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/zh-Hans.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/zh-HK.lproj/Localizable.strings -r
localisort -t ./Application/Euphoria/en.lproj/Localizable.strings -i ./Application/Euphoria/zh-TW.lproj/Localizable.strings -r
